# CHANGE ME - You need to configure this for your particular mongo env setting
development:
  host:     localhost
  port:     27017

test:
  host:     localhost
  port:     27017

production:
  host:     localhost
  port:     27017